name: CI/CD Pipeline

on:
  push:
    branches:
      - "**" # Trigger on push to any branch
  pull_request:
    branches:
      - main # Trigger on PRs targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14" # Specify your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build # Ensure build job completes before deploying
    if: github.ref == 'refs/heads/main' # Only deploy if the branch is main

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to production
        run: |
          ./deploy.sh --prod  # Example deployment script
